service: email-sender # NOTE: Don't put the word "google" in here

provider:
  name: google
  runtime: nodejs
  project: personal-site-214302
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .eslintrc
    - .gcloudignore
    - .serverless
    - .vscode
    - coverage
    - Jenkinsfile
    - README.md
    - "**/tests"

functions:
  http:
    handler: emailSender
    events:
      - http: path
